# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0002_recordcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endrecord',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='startrecord',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
