# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0003_auto_20180521_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordCost',
            new_name='CostRecord',
        ),
    ]
