# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0004_auto_20180525_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costrecord',
            name='call_id',
        ),
        migrations.AddField(
            model_name='endrecord',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CostRecord',
        ),
    ]
