# Generated by Django 2.0.5 on 2018-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0005_auto_20180526_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.BigIntegerField(unique=True)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
