# Generated by Django 2.0.5 on 2018-06-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0006_callrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallRecord',
        ),
        migrations.AlterField(
            model_name='endrecord',
            name='call_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapi.StartRecord', unique=True),
        ),
    ]
