# Generated by Django 2.0.5 on 2018-06-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0007_auto_20180601_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endrecord',
            name='call_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapi.StartRecord', to_field='call_id', unique=True),
        ),
    ]
