# Generated by Django 2.0.5 on 2018-06-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0008_auto_20180601_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endrecord',
            name='call_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='serviceapi.StartRecord'),
        ),
    ]
