# Generated by Django 2.0.5 on 2018-06-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0009_auto_20180602_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endrecord',
            name='call_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapi.StartRecord', to_field='call_id'),
        ),
    ]
