# Generated by Django 2.0.5 on 2018-06-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapi', '0010_auto_20180602_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endrecord',
            old_name='call_id',
            new_name='start',
        ),
    ]
